---

- hosts: edge
  gather_facts: no
  become: yes
  
  tasks:
    - name: Install ambari server
      yum: name=ambari-server state=latest

    - name: Install mysql connector
      copy:
        src: mysql-connector-java-8.0.12.jar
        dest: /var/lib/ambari-server/resources/mysql-connector-java-8.0.12.jar
        owner: root
        group: root
        mode: 0644

    



