---

- hosts: hadoop
  gather_facts: no
  become: yes
  
  tasks:
    - pam_limits:
        domain: hadoop
        limit_type: '-'
        limit_item: nofile
        value: 64000
        use_max: yes   

    - sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        state: present

