---

- hosts: hadoop
  gather_facts: no
  become: yes
  
  tasks:
    - pam_limits:
        domain: hadoop
        limit_type: '-'
        limit_item: nofile
        value: 64000
        use_max: yes   

    - sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        state: present

    - name: Install ambari repo
      copy:
        src: ambari.repo
        dest: /etc/yum.repos.d/ambari.repo
        owner: root
        group: root
        mode: 0644

    - name: Install ambari-agent
      yum: name=ambari-agent state=latest

    - name: Adjust ambari-agent file
      lineinfile:
        dest: /etc/ambari-agent/conf/ambari-agent.ini
        regexp: ^hostname
        line: "hostname=hdplab1.myhadooplab.com"
        state: present
      notify: enable ambari-agent

  handlers:
    - name: enable ambari-agent
      service: name=ambari-agent enabled=yes state=started

