---

- hosts: hadoop
  gather_facts: no
  become: yes
  
  tasks:
    - pam_limits:
        domain: hadoop
        limit_type: '-'
        limit_item: nofile
        value: 64000
        use_max: yes   

    - sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.default.disable_ipv6
        value: 1
        state: present

    - sysctl:
        name: net.ipv6.conf.lo.disable_ipv6
        value: 1
        state: present

    - name: Install mysql connector
      copy:
        src: mysql-connector-java-8.0.12.jar
        dest: /var/lib/ambari-server/resources/mysql-connector-java-8.0.12.jar
        owner: root
        group: root
        mode: 0644

    - name: Install ambari repo
      copy:
        src: ambari.repo
        dest: /etc/yum.repos.d/ambari.repo
        owner: root
        group: root
        mode: 0644

    - name: Install ambari-agent
      yum: name=ambari-agent state=latest
    


